# Generated by Django 4.2.4 on 2023-08-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('limit', models.IntegerField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
