# Generated by Django 4.2.4 on 2023-08-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='d',
            new_name='id',
        ),
    ]
